import type { Metadata } from "next";
import "./globals.css";
import { Bebas_Neue, Climate_Crisis } from 'next/font/google';

const bebasNeue = Bebas_Neue({ subsets: ['latin'], weight: '400' });
// const climateCrisis = Climate_Crisis({ subsets: ['latin'], weight: '400' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${bebasNeue.className} font-['Duplet'] bg-white`}>
        <div className="px-4 md:px-8 lg:px-16">
          {/* Example usage of Climate Crisis font: */}
          {/* <h1 className={climateCrisis.className}>This is Climate Crisis font</h1> */}
          {children}
        </div>
      </body>
    </html>
  );
}
